name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gobank_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Install migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/local/bin/

    - name: Run migrations
      run: migrate -path db/migrations -database "postgresql://postgres:postgres@localhost:5432/gobank_test?sslmode=disable" up

    - name: Run tests
      run: go test -v ./...
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: gobank_test
        JWT_ACCESS_SECRET: test-secret
        JWT_REFRESH_SECRET: test-refresh-secret

    - name: Build
      run: go build -v ./cmd/api

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: gobank:latest

    - name: Login to DockerHub
      if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to DockerHub
      if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/gobank:latest,${{ secrets.DOCKER_USERNAME }}/gobank:${{ github.sha }}

    - name: Docker build completed
      run: |
        echo "✅ Docker image built successfully"
        echo "Image: gobank:latest"
        if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "🚀 Image pushed to DockerHub: ${{ secrets.DOCKER_USERNAME }}/gobank:latest"
        else
          echo "ℹ️  Image not pushed - DockerHub credentials not configured"
          echo "To push images, add DOCKER_USERNAME and DOCKER_PASSWORD secrets"
        fi